name: called-workflow-tag

on:
  workflow_call:
    operation:
      description: 'The operation to perform'
      required: true
      default: 'deploy'
      type: string
      
jobs:
  scenario:
    runs-on: ubuntu-latest
    steps:
      - name: show-scenario
        run: |
          echo "Scenario: Call workflow in different repository using tags"
          echo "CURRENT WORKFLOW: ${{ github.workflow }}"
          echo "Operation: ${{ github.event.inputs.operation }}"
